<a href="https://colab.research.google.com/github/Ajish18/Employee_Management/blob/main/ai_trip_cost_estimator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df_transport = pd.read_csv("transport_fare_dataset_india.csv.csv")
df_transport.head()

,source_city,destination_city,distance_km,transport_mode,day_type,is_festival,base_fare,final_fare
0,Chennai,Coimbatore,501,Bus,Weekend,No,630,693
1,Chennai,Coimbatore,501,Bus,Weekend,Yes,630,819
2,Chennai,Coimbatore,494,Train,Weekday,No,325,325
3,Chennai,Coimbatore,494,Train,Weekend,No,325,358
4,Chennai,Coimbatore,494,Train,Weekend,Yes,325,423

In [ ]:
df_hotel = pd.read_csv("hotel_stay_cost_dataset_india.csv")
df_hotel.head()

         city    hotel_type budget_type  cost_per_night
0     Chennai  Budget Hotel         Low             950
1     Chennai  3-Star Hotel      Medium            3200
2     Chennai  5-Star Hotel        High            8500
3  Coimbatore  Budget Hotel         Low             800
4  Coimbatore  3-Star Hotel      Medium            2800

In [ ]:
df_food = pd.read_csv("food_cost_dataset_india..csv")
df_food.head()

         city budget_type  avg_food_cost_per_day
0     Chennai         Low                    250
1     Chennai      Medium                    650
2     Chennai        High                   1800
3  Coimbatore         Low                    200
4  Coimbatore      Medium                    550

In [ ]:
df_local = pd.read_csv("local_transport_cost_dataset_india.csv")
df_local.head()

         city transport_type  avg_cost_per_day
0     Chennai            Bus               120
1     Chennai           Auto               300
2     Chennai          Metro               150
3     Chennai            Cab               950
4  Coimbatore            Bus               100

In [ ]:
df_crowd = pd.read_csv("crowd_analysis_dataset_india.csv")
df_crowd.head()

      city place_category day_type is_festival crowd_level
0  Chennai          Beach  Weekday          No         Low
1  Chennai          Beach  Weekend          No      Medium
2  Chennai          Beach  Weekend         Yes        High
3  Chennai         Temple  Weekday          No         Low
4  Chennai         Temple  Weekend          No      Medium

In [ ]:
df_places = pd.read_csv("tourist_places_dataset.csv")
df_places.head()

,city,place_name,place_category,best_time_to_visit,entry_fee,budget_type
0,Chennai,Marina Beach,Beach,Evening,0,Low
1,Chennai,Kapaleeshwarar Temple,Spiritual,Morning,0,Low
2,Chennai,Fort St. George,Heritage,Morning,30,Medium
3,Chennai,DakshinaChitra,Cultural,Afternoon,150,High
4,Coimbatore,Adiyogi Shiva,Spiritual,Evening,0,Low

In [ ]:
df_transport.columns

Index(['source_city', 'destination_city', 'distance_km', 'transport_mode',
       'day_type', 'is_festival', 'base_fare', 'final_fare'],
      dtype='object')

In [ ]:
df_base = df_transport.copy()
df_base.head()

In [ ]:
import pandas as pd
df_hotel = pd.read_csv("hotel_stay_cost_dataset_india.csv")
df_base = df_transport.copy()
df_merged = df_base.merge(
    df_hotel,
    left_on="destination_city",
    right_on="city",
    how="left"
)

df_merged.head()

,source_city,destination_city,distance_km,transport_mode,day_type,is_festival,base_fare,final_fare,city,hotel_type,budget_type,cost_per_night
0,Chennai,Coimbatore,501,Bus,Weekend,No,630,693,Coimbatore,Budget Hotel,Low,800.0
1,Chennai,Coimbatore,501,Bus,Weekend,No,630,693,Coimbatore,3-Star Hotel,Medium,2800.0
2,Chennai,Coimbatore,501,Bus,Weekend,No,630,693,Coimbatore,5-Star Hotel,High,6500.0
3,Chennai,Coimbatore,501,Bus,Weekend,Yes,630,819,Coimbatore,Budget Hotel,Low,800.0
4,Chennai,Coimbatore,501,Bus,Weekend,Yes,630,819,Coimbatore,3-Star Hotel,Medium,2800.0

In [ ]:
df_merged = df_merged.merge(
    df_food,
    left_on="destination_city",
    right_on="city",
    how="left"
)

df_merged.head()

,source_city,destination_city,distance_km,transport_mode,day_type,is_festival,base_fare,final_fare,city,hotel_type,budget_type,cost_per_night
0,Chennai,Coimbatore,501,Bus,Weekend,No,630,693,Coimbatore,Budget Hotel,Low,800.0
1,Chennai,Coimbatore,501,Bus,Weekend,No,630,693,Coimbatore,3-Star Hotel,Medium,2800.0
2,Chennai,Coimbatore,501,Bus,Weekend,No,630,693,Coimbatore,5-Star Hotel,High,6500.0
3,Chennai,Coimbatore,501,Bus,Weekend,Yes,630,819,Coimbatore,Budget Hotel,Low,800.0
4,Chennai,Coimbatore,501,Bus,Weekend,Yes,630,819,Coimbatore,3-Star Hotel,Medium,2800.0

In [ ]:
df_merged = df_merged.merge(
    df_local,
    left_on="destination_city",
    right_on="city",
    how="left"
)

df_merged.head()

In [ ]:
df_crowd = pd.read_csv("crowd_analysis_dataset_india.csv")
df_merged = df_merged.merge(
    df_crowd,
    left_on="destination_city",
    right_on="city",
    how="left"
)

df_merged.head()

,source_city,destination_city,distance_km,transport_mode,day_type_x,is_festival_x,base_fare,final_fare,city_x,hotel_type,budget_type,cost_per_night,city_y,place_category,day_type_y,is_festival_y,crowd_level
0,Chennai,Coimbatore,501,Bus,Weekend,No,630,693,Coimbatore,Budget Hotel,Low,800.0,Coimbatore,Spiritual,Weekday,No,Low
1,Chennai,Coimbatore,501,Bus,Weekend,No,630,693,Coimbatore,Budget Hotel,Low,800.0,Coimbatore,Spiritual,Weekend,No,Medium
2,Chennai,Coimbatore,501,Bus,Weekend,No,630,693,Coimbatore,Budget Hotel,Low,800.0,Coimbatore,Spiritual,Weekend,Yes,High
3,Chennai,Coimbatore,501,Bus,Weekend,No,630,693,Coimbatore,Budget Hotel,Low,800.0,Coimbatore,Museum,Weekday,No,Low
4,Chennai,Coimbatore,501,Bus,Weekend,No,630,693,Coimbatore,Budget Hotel,Low,800.0,Coimbatore,Museum,Weekend,No,Medium

In [ ]:
df_merged.columns

Index(['source_city', 'destination_city', 'distance_km', 'transport_mode',
       'day_type_x', 'is_festival_x', 'base_fare', 'final_fare', 'city_x',
       'hotel_type', 'budget_type', 'cost_per_night', 'city_y',
       'place_category', 'day_type_y', 'is_festival_y', 'crowd_level'],
      dtype='object')

In [ ]:
df_final = df_merged[[
    "source_city",
    "destination_city",
    "transport_mode",
    "day_type",
    "is_festival",
    "cost_per_night",
    "avg_food_cost_per_day",
    "avg_cost_per_day",
    "crowd_level",
    "final_fare"
]]

df_final.head()

In [ ]:
df_final = df_merged[[
    "source_city",
    "destination_city",
    "transport_mode",
    "day_type_x", # Using day_type from transport data
    "is_festival_x", # Using is_festival from transport data
    "cost_per_night",
    "crowd_level",
    "final_fare"
]]
df_final.isnull().sum()

source_city          0
destination_city     0
transport_mode       0
day_type_x           0
is_festival_x        0
cost_per_night      18
crowd_level         18
final_fare           0
dtype: int64

In [ ]:
df_final = df_final.dropna()
df_final.isnull().sum()

source_city          0
destination_city     0
transport_mode       0
day_type_x           0
is_festival_x        0
cost_per_night      18
crowd_level         18
final_fare           0
dtype: int64

In [ ]:
df_final.columns

Index(['source_city', 'destination_city', 'transport_mode', 'day_type_x',
       'is_festival_x', 'cost_per_night', 'crowd_level', 'final_fare'],
      dtype='object')

In [ ]:
df_final = df_merged[[
    "source_city",
    "destination_city",
    "transport_mode",
    "day_type_x",
    "is_festival_x",
    "cost_per_night",
    "crowd_level",
    "final_fare"
]]

In [ ]:
df_final = df_final.dropna()
df_final.isnull().sum()

source_city          0
destination_city     0
transport_mode       0
day_type_x           0
is_festival_x        0
cost_per_night      18
crowd_level         18
final_fare           0
dtype: int64

In [ ]:
df_merged = df_merged.dropna()
df_merged.isnull().sum()

In [ ]:
df_final = df_merged[[
    "source_city",
    "destination_city",
    "transport_mode",
    "day_type_x",
    "is_festival_x",
    "cost_per_night",
    "crowd_level",
    "final_fare"
]]

df_final.isnull().sum()

source_city          0
destination_city     0
transport_mode       0
day_type_x           0
is_festival_x        0
cost_per_night      18
crowd_level         18
final_fare           0
dtype: int64

In [ ]:
df_final.isnull().sum()

source_city          0
destination_city     0
transport_mode       0
day_type_x           0
is_festival_x        0
cost_per_night      18
crowd_level         18
final_fare           0
dtype: int64

In [ ]:
df_final[df_final["cost_per_night"].isnull()][["destination_city"]].head(20)

    destination_city
288          Madurai
289          Madurai
290          Madurai
291          Madurai
292          Madurai
293          Madurai
294          Madurai
295          Madurai
296          Madurai
486           Trichy
487           Trichy
488           Trichy
489           Trichy
490           Trichy
491           Trichy
492           Trichy
493           Trichy
494           Trichy

In [ ]:
df_final = df_final.dropna(subset=["cost_per_night", "crowd_level"])
df_final.isnull().sum()

source_city          0
destination_city     0
transport_mode       0
day_type_x           0
is_festival_x        0
cost_per_night      18
crowd_level         18
final_fare           0
dtype: int64

In [ ]:
df_final = df_final.dropna(subset=["cost_per_night", "crowd_level"])

In [ ]:
df_final.isnull().sum()

source_city         0
destination_city    0
transport_mode      0
day_type_x          0
is_festival_x       0
cost_per_night      0
crowd_level         0
final_fare          0
dtype: int64

In [ ]:
X = df_final.drop("final_fare", axis=1)
y = df_final["final_fare"]

X.head(), y.head()

(  source_city destination_city transport_mode day_type_x is_festival_x  \
 0     Chennai       Coimbatore            Bus    Weekend            No
 1     Chennai       Coimbatore            Bus    Weekend            No
 2     Chennai       Coimbatore            Bus    Weekend            No
 3     Chennai       Coimbatore            Bus    Weekend            No
 4     Chennai       Coimbatore            Bus    Weekend            No

    cost_per_night crowd_level
 0           800.0         Low
 1           800.0      Medium
 2           800.0        High
 3           800.0         Low
 4           800.0      Medium  ,
 0    693
 1    693
 2    693
 3    693
 4    693
 Name: final_fare, dtype: int64)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import pandas as pd # Import pandas for get_dummies

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Apply one-hot encoding to categorical features
X_train = pd.get_dummies(X_train, columns=['source_city', 'destination_city', 'transport_mode', 'day_type_x', 'is_festival_x', 'crowd_level'], drop_first=True)
X_test = pd.get_dummies(X_test, columns=['source_city', 'destination_city', 'transport_mode', 'day_type_x', 'is_festival_x', 'crowd_level'], drop_first=True)

# Ensure X_train and X_test have the same columns after one-hot encoding
# This is crucial if some categories are present in train but not test, or vice-versa
train_cols = X_train.columns
test_cols = X_test.columns
missing_in_test = set(train_cols) - set(test_cols)
for c in missing_in_test:
    X_test[c] = 0
missing_in_train = set(test_cols) - set(train_cols)
for c in missing_in_train:
    X_train[c] = 0
X_test = X_test[train_cols] # Align order of columns

model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [ ]:
from sklearn.metrics import mean_absolute_error

y_pred = model.predict(X_test)
mean_absolute_error(y_test, y_pred)

0.06405228758169933

In [ ]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

0.06405228758169933

In [ ]:
# Example user input
user_input = {
    "source_city": "Chennai",
    "destination_city": "Coimbatore",
    "transport_mode": "Bus",
    "day_type_x": "Weekend",
    "is_festival_x": "No",
    "cost_per_night": 800,
    "crowd_level": "Medium"
}

In [ ]:
user_input = {
    "source_city": "Chennai",
    "destination_city": "Coimbatore",
    "transport_mode": "Bus",
    "day_type_x": "Weekend",
    "is_festival_x": "No",
    "cost_per_night": 800,
    "crowd_level": "Medium"
}
user_df = pd.DataFrame([user_input])

# Define the categorical columns used during training
categorical_cols = ['source_city', 'destination_city', 'transport_mode', 'day_type_x', 'is_festival_x', 'crowd_level']

# Apply one-hot encoding to user_df, consistent with X_train
user_df_encoded = pd.get_dummies(user_df, columns=categorical_cols, drop_first=True)

# Add missing columns (important) - these should be present in X_train but not in user_df_encoded
for col in X_train.columns:
    if col not in user_df_encoded.columns:
        user_df_encoded[col] = 0

# Ensure same column order as X_train
user_df_encoded = user_df_encoded[X_train.columns]

In [ ]:
predicted_cost = model.predict(user_df_encoded)
predicted_cost

array([801.93])